/**
 * Company and Tenant type definitions
 */

import { CompanyStatus, SubscriptionPlan } from '../enums/status.enums';

/**
 * Company settings
 */
export interface CompanySettings {
  // Regional settings
  timezone: string;
  language: string;
  currency: string;
  dateFormat: string;
  
  // Inventory settings
  defaultWarehouseId?: string;
  stockValuationMethod: 'fifo' | 'lifo' | 'weighted_average';
  enableNegativeStock: boolean;
  enableBatchTracking: boolean;
  enableExpiryTracking: boolean;
  
  // Document settings
  autoGenerateDocumentNumbers: boolean;
  documentNumberPrefix: {
    goodsReceipt: string;
    goodsIssue: string;
    stockAdjustment: string;
  };
  
  // Notification settings
  lowStockAlertEnabled: boolean;
  lowStockThreshold: number;
  notificationEmail?: string;
}

/**
 * Company entity (Tenant)
 */
export interface Company {
  id: string;
  code: string;
  name: string;
  nameTh?: string;
  taxId?: string;
  
  // Contact information
  email: string;
  phone?: string;
  fax?: string;
  website?: string;
  
  // Address
  address: string;
  addressTh?: string;
  district?: string;
  amphoe?: string;
  province?: string;
  postalCode?: string;
  country: string;
  
  // Subscription
  subscriptionPlan: SubscriptionPlan;
  status: CompanyStatus;
  trialEndsAt?: Date;
  subscriptionEndsAt?: Date;
  
  // Limits
  maxUsers: number;
  maxProducts: number;
  maxWarehouses: number;
  
  // Settings
  settings: CompanySettings;
  
  // Branding
  logoUrl?: string;
  
  // Timestamps
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Company creation DTO
 */
export interface CreateCompanyDto {
  code: string;
  name: string;
  nameTh?: string;
  taxId?: string;
  email: string;
  phone?: string;
  website?: string;
  address: string;
  addressTh?: string;
  district?: string;
  amphoe?: string;
  province?: string;
  postalCode?: string;
  country: string;
}

/**
 * Company update DTO
 */
export interface UpdateCompanyDto {
  name?: string;
  nameTh?: string;
  taxId?: string;
  email?: string;
  phone?: string;
  fax?: string;
  website?: string;
  address?: string;
  addressTh?: string;
  district?: string;
  amphoe?: string;
  province?: string;
  postalCode?: string;
  country?: string;
  logoUrl?: string;
  settings?: Partial<CompanySettings>;
}

/**
 * Warehouse entity
 */
export interface Warehouse {
  id: string;
  code: string;
  name: string;
  nameTh?: string;
  description?: string;
  companyId: string;
  
  // Address
  address: string;
  district?: string;
  amphoe?: string;
  province?: string;
  postalCode?: string;
  
  // Status
  isActive: boolean;
  isDefault: boolean;
  
  // Timestamps
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Warehouse creation DTO
 */
export interface CreateWarehouseDto {
  code: string;
  name: string;
  nameTh?: string;
  description?: string;
  address: string;
  district?: string;
  amphoe?: string;
  province?: string;
  postalCode?: string;
  isDefault?: boolean;
}

/**
 * Warehouse update DTO
 */
export interface UpdateWarehouseDto {
  name?: string;
  nameTh?: string;
  description?: string;
  address?: string;
  district?: string;
  amphoe?: string;
  province?: string;
  postalCode?: string;
  isActive?: boolean;
  isDefault?: boolean;
}

/**
 * Tenant context for request
 */
export interface TenantContext {
  companyId: string;
  company: Company;
  warehouseId?: string;
  warehouse?: Warehouse;
}
